name: Pytest and coveralls

on:
  workflow_dispatch: ~
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.9"] # "3.7", "3.9" deactivated for faster turnaround
        install-extras: ["tests,plotting,zurich-instruments,tektronix,tabor-instruments", "tests,plotting,zurich-instruments,tektronix,tabor-instruments,Faster-fractions"]

    steps:
    - name: Install gmpy2 build dependencies if required
      run: |
        if [[ ${{ matrix.install-extras }} == *Faster-fractions* ]]; then
          sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev
        fi
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        # caching is currently (2021.11) only available on actions/setup-python@main branch
        # cache: pip
        # cache-dependency-path: setup.cfg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage coveralls

    - name: Install package
      run: |
        python -m pip install .[${{ matrix.install-extras }}]

    - name: Test with pytest
      run: |
        coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: python-${{ matrix.python-version }}-${{ matrix.install-extras }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
